spec:
  template:
    spec:
      containers:
        - readinessProbe:
            httpGet:
              path: /login
              port: 8080
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /signup
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 30
